export const TELEGRAM_TL_CLIENT_TOKEN = Symbol('TELEGRAM_TL_CLIENT_TOKEN');
export const TELEGRAM_TL_CLIENT_MODULE = Symbol('TELEGRAM_TL_CLIENT_MODULE');
export const TELEGRAM_TL_CLIENT_MODULE_OPTIONS = Symbol(
  'TELEGRAM_TL_CLIENT_MODULE_OPTIONS',
);
export const TELEGRAM_TL_CLIENT_EVENT_LISTENER_METADATA =
  'TELEGRAM_TL_CLIENT_EVENT_LISTENER_METADATA';
